default:
  store_options: &default_store_options
    max_age: <%= 60.days.to_i %>
    namespace: <%= Rails.env %>
  size_estimate_samples: 1000

development: &development
  database: cache
  store_options:
    <<: *default_store_options
    max_size: <%= 256.megabytes %>

production: &production
  database: cache
  store_options:
    <<: *default_store_options
    max_entries: <%= 256.megabytes %>
