default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  user: dev 
  password: <%= ENV["DB_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  primary:
    <<: *default
    database: forum_r8_development
  queue:
    <<: *default
    database: forum_r8_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: forum_r8_development_cable
    migrations_paths: db/cable_migrate
  cache:
    <<: *default
    database: forum_r8_development_cache
    migrations_paths: db/cache_migrate

test:
  <<: *default
  database: forum_r8_test

production:
  primary: &primary_production
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    migrations_paths: db/cable_migrate
