# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  # recalculate_posts_comments_count:
  #   class: RecalculatePostsCommentsCountJob
  #   queue: cron
  #   schedule: every hour 
  # create_commets:
  #   class: CreateCommentsJob
  #   queue: cron
  #   schedule: every day

development:
  recalculate_posts_comments_count:
    class: RecalculatePostsCommentsCountJob
    queue: cron
    schedule: every hour 
